commerce_payment.commerce_payment_gateway.plugin.paytm_payment:
  type: config_object
  # type: commerce_payment_gateway_configuration
  mapping:
    merchant_id:
      type: string
      label: 'Merchant Id'
    merchant_key:
      type: string
      label: 'Merchant Key'
    merchant_website:
      type: string
      label: 'Merchant Website'
    merchant_transaction_url:
      type: string
      label: 'Transaction URL'
    merchant_transaction_status_url:
      type: string
      label: 'Transaction Status URL'
    merchant_transaction_custom_callback_url:
      type: string
      label: 'Custom Call Back URL (if you want)'